### ISSUE TITLE
[Question]: What do we want to do in terms of speaker names and bibliographical references?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/ODIN-23-summary-paper#15]
From @colleenjg in https://github.com/catalystneuro/ODIN-23-summary-paper/pull/14/files#diff-0403ef06adf405f7b310b4518bd6a3559854f54c61676f676ce9cbfee7172ab6R17

> Question: What do we want to do in terms of speaker names and bibliographical references? I've referenced when it seemed applicable, but mostly refer to project names and not the authors/creators.

cc @rly @neurovium 

Personally I think the reference in the citation for each sentence should be sufficient

**Comment by rly** [comment]
> Personally I think the reference in the citation for each sentence should be sufficient

I agree

**Comment by colleenjg** [comment]
*Nima:* It could be great to specifically mention the speakers who participated in ODIN when we discuss their presentations, in addition to the citations.
