### ISSUE TITLE
Add a bibliography

### ISSUE THREAD

**Issue by colleenjg** [catalystneuro/ODIN-23-summary-paper#16]
I would suggest that we keep it simple, by adding a `references.bib` where the citation keys are formatted something like `FirstAuthorYYYY`. Then we just use in-text citations in the format: {cite}`CitationKey`. 

Eventually, we will need to convert this into proper citations, when generating the final paper, but as long as this approach is manageable (i.e., we are able to keep track of our references), it avoids the need to compile files as we write.

**Comment by CodyCBakerPhD** [comment]
👍 Sounds good

**Comment by CodyCBakerPhD** [comment]
added in #17
