### ISSUE TITLE
[Discussion] Outline?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/ODIN-23-summary-paper#6]
Happy to use this thread to generally discuss what everyone thinks of the main paper structure, before we get too deep into it

My first proposed structure is

# Introduction

What is ODIN/other quick intro summary to set the tone.

# Summary of symposium and large group discussions

[goal with this section is to keep each summary limited to 3-5 sentences; very concise with focus on the most novel aspects]

1.1 New devices and high throughput acquisitions

1.2 Neuroinformatics of Neurophysiologyneurophysiology

1.3 Platforms/Infrastructures

2.1 “OpenData2Knowledge”

2.2 Neuroscience Toolkits

2.3 Modeling and benchmarking

# Breakout Session - Infrastructure, formats, and standardization of data on the DANDI archive

Summary of the breakout session.

# Breakout Session - AI/ML, ​​computing & visualization

Summary of the breakout session.

# Looking forward

Mention how this is desired to be a regular event for the community.

## Harnessing large language models (LLMs) to improve the user experience

Mention current work in progress harnessing ChatGPT-like entities to help the neuroscience data experience end-to-end.

## Leveraging the DANDI archive for education of neuroscience

Discuss ongoing efforts to harness data infrastructure to make education of neuroscience both easier and more rigorous.

**Comment by CodyCBakerPhD** [comment]
As for abstract/significance statement / other required sections, that may depend on the article type that is determined dependent on the journal we plan to submit to so was going to hold off drafting those until we get a better idea

**Comment by CodyCBakerPhD** [comment]
attn: @colleenjg @neurovium @rly, let me know what you think

**Comment by colleenjg** [comment]
Thanks for putting this together, @CodyCBakerPhD! I think this makes a lot of sense for a summary paper, with the structure basically following the structure of the symposium. 

I'm wondering though whether, to reach a broader audience, we should also include some broader perspective sections in the intro and discussion that address concerns from members of the community who are more skeptical of the feasibility and usefulness of implementing open science practices. 

This could take the form of a few lines in the intro, and a section under **Looking Forward** with a more "perspective piece" slant that (1) synthesizes some of the major obstacles faced by the community when it comes to adopting open science practices and leveraging open science, and (2) provides a vision of how we believe these can be addressed going forward. I would see this section as perhaps being more editorial than the rest, and also likely more abstract.

**Comment by CodyCBakerPhD** [comment]
> I'm wondering though whether, to reach a broader audience, we should also include some broader perspective sections in the intro and discussion that address concerns from members of the community who are more skeptical of the feasibility and usefulness of implementing open science practices.

Indeed, I was taking a very direct approach to describing _what happened_, but taking a step back and asking _why are we doing this_ in a broader sense could make it more accessible



> This could take the form of a few lines in the intro, and a section under Looking Forward with a more "perspective piece" slant that (1) synthesizes some of the major obstacles faced by the community when it comes to adopting open science practices and leveraging open science, and (2) provides a vision of how we believe these can be addressed going forward. I would see this section as perhaps being more editorial than the rest, and also likely more abstract.

That sounds like a great approach to address this, feel free to add those in!
